LANGNAME2LANGCODE = {
    'Acehnese (Arabic)': 'ace_Arab',
    'Acehnese (Latin)': 'ace_Latn',
    'Mesopotamian Arabic': 'acm_Arab',
    'Ta’izzi-Adeni Arabic': 'acq_Arab',
    'Tunisian Arabic': 'aeb_Arab',
    'Afrikaans': 'afr_Latn',
    'South Levantine Arabic': 'ajp_Arab',
    'Akan': 'aka_Latn',
    'Tosk Albanian': 'als_Latn',
    'Amharic': 'amh_Ethi',
    'North Levantine Arabic': 'apc_Arab',
    'MSA (Arabic)': 'arb_Arab',
    'MSA (Romanized)': 'arb_Latn',
    'Najdi Arabic': 'ars_Arab',
    'Moroccan Arabic': 'ary_Arab',
    'Egyptian Arabic': 'arz_Arab',
    'Assamese': 'asm_Beng',
    'Asturian': 'ast_Latn',
    'Awadhi': 'awa_Deva',
    'Central Aymara': 'ayr_Latn',
    'South Azerbaijani': 'azb_Arab',
    'North Azerbaijani': 'azj_Latn',
    'Bashkir': 'bak_Cyrl',
    'Bambara': 'bam_Latn',
    'Balinese': 'ban_Latn',
    'Belarusian': 'bel_Cyrl',
    'Bemba': 'bem_Latn',
    'Bengali': 'ben_Beng',
    'Bhojpuri': 'bho_Deva',
    'Banjar (Arabic script)': 'bjn_Arab',
    'Banjar (Latin script)': 'bjn_Latn',
    'Standard Tibetan': 'bod_Tibt',
    'Bosnian': 'bos_Latn',
    'Buginese': 'bug_Latn',
    'Bulgarian': 'bul_Cyrl',
    'Catalan': 'cat_Latn',
    'Cebuano': 'ceb_Latn',
    'Czech': 'ces_Latn',
    'Chokwe': 'cjk_Latn',
    'Central Kurdish': 'ckb_Arab',
    'Crimean Tatar': 'crh_Latn',
    'Welsh': 'cym_Latn',
    'Danish': 'dan_Latn',
    'German': 'deu_Latn',
    'Southwestern Dinka': 'dik_Latn',
    'Dyula': 'dyu_Latn',
    'Dzongkha': 'dzo_Tibt',
    'Greek': 'ell_Grek',
    'English': 'eng_Latn',
    'Esperanto': 'epo_Latn',
    'Estonian': 'est_Latn',
    'Basque': 'eus_Latn',
    'Ewe': 'ewe_Latn',
    'Faroese': 'fao_Latn',
    'Fijian': 'fij_Latn',
    'Finnish': 'fin_Latn',
    'Fon': 'fon_Latn',
    'French': 'fra_Latn',
    'Friulian': 'fur_Latn',
    'Nigerian Fulfulde': 'fuv_Latn',
    'West Central Oromo': 'gaz_Latn',
    'Scottish Gaelic': 'gla_Latn',
    'Irish': 'gle_Latn',
    'Galician': 'glg_Latn',
    'Guarani': 'grn_Latn',
    'Gujarati': 'guj_Gujr',
    'Haitian Creole': 'hat_Latn',
    'Hausa': 'hau_Latn',
    'Hebrew': 'heb_Hebr',
    'Hindi': 'hin_Deva',
    'Chhattisgarhi': 'hne_Deva',
    'Croatian': 'hrv_Latn',
    'Hungarian': 'hun_Latn',
    'Armenian': 'hye_Armn',
    'Igbo': 'ibo_Latn',
    'Ilocano': 'ilo_Latn',
    'Indonesian': 'ind_Latn',
    'Icelandic': 'isl_Latn',
    'Italian': 'ita_Latn',
    'Javanese': 'jav_Latn',
    'Japanese': 'jpn_Jpan',
    'Kabyle': 'kab_Latn',
    'Jingpho': 'kac_Latn',
    'Kamba': 'kam_Latn',
    'Kannada': 'kan_Knda',
    'Kashmiri (Arabic)': 'kas_Arab',
    'Kashmiri (Devanagari)': 'kas_Deva',
    'Georgian': 'kat_Geor',
    'Kazakh': 'kaz_Cyrl',
    'Kabiyè': 'kbp_Latn',
    'Kabuverdianu': 'kea_Latn',
    'Halh Mongolian': 'khk_Cyrl',
    'Khmer': 'khm_Khmr',
    'Kikuyu': 'kik_Latn',
    'Kinyarwanda': 'kin_Latn',
    'Kyrgyz': 'kir_Cyrl',
    'Kimbundu': 'kmb_Latn',
    'Northern Kurdish': 'kmr_Latn',
    'Kanuri (Arabic)': 'knc_Arab',
    'Kanuri (Latin)': 'knc_Latn',
    'Kikongo': 'kon_Latn',
    'Korean': 'kor_Hang',
    'Lao': 'lao_Laoo',
    'Ligurian': 'lij_Latn',
    'Limburgish': 'lim_Latn',
    'Lingala': 'lin_Latn',
    'Lithuanian': 'lit_Latn',
    'Lombard': 'lmo_Latn',
    'Latgalian': 'ltg_Latn',
    'Luxembourgish': 'ltz_Latn',
    'Luba-Kasai': 'lua_Latn',
    'Ganda': 'lug_Latn',
    'Luo': 'luo_Latn',
    'Mizo': 'lus_Latn',
    'Standard Latvian': 'lvs_Latn',
    'Magahi': 'mag_Deva',
    'Maithili': 'mai_Deva',
    'Malayalam': 'mal_Mlym',
    'Marathi': 'mar_Deva',
    'Minangkabau (Arabic)': 'min_Arab',
    'Minangkabau (Latin)': 'min_Latn',
    'Macedonian': 'mkd_Cyrl',
    'Maltese': 'mlt_Latn',
    'Meitei (Bengali script)': 'mni_Beng',
    'Mossi': 'mos_Latn',
    'Maori': 'mri_Latn',
    'Burmese': 'mya_Mymr',
    'Dutch': 'nld_Latn',
    'N’ko': 'nqo_Nkoo',
    'Norwegian Nynorsk': 'nno_Latn',
    'Norwegian Bokmål': 'nob_Latn',
    'Nepali': 'npi_Deva',
    'Northern Sotho': 'nso_Latn',
    'Nuer': 'nus_Latn',
    'Nyanja': 'nya_Latn',
    'Occitan': 'oci_Latn',
    'Odia': 'ory_Orya',
    'Pangasinan': 'pag_Latn',
    'Eastern Panjabi': 'pan_Guru',
    'Papiamento': 'pap_Latn',
    'Southern Pashto': 'pbt_Arab',
    'Western Persian': 'pes_Arab',
    'Plateau Malagasy': 'plt_Latn',
    'Polish': 'pol_Latn',
    'Portuguese': 'por_Latn',
    'Dari': 'prs_Arab',
    'Ayacucho Quechua': 'quy_Latn',
    'Romanian': 'ron_Latn',
    'Rundi': 'run_Latn',
    'Russian': 'rus_Cyrl',
    'Sango': 'sag_Latn',
    'Sanskrit': 'san_Deva',
    'Santali': 'sat_Olck',
    'Sicilian': 'scn_Latn',
    'Shan': 'shn_Mymr',
    'Sinhala': 'sin_Sinh',
    'Slovak': 'slk_Latn',
    'Slovenian': 'slv_Latn',
    'Samoan': 'smo_Latn',
    'Shona': 'sna_Latn',
    'Sindhi': 'snd_Arab',
    'Somali': 'som_Latn',
    'Southern Sotho': 'sot_Latn',
    'Spanish': 'spa_Latn',
    'Sardinian': 'srd_Latn',
    'Serbian': 'srp_Cyrl',
    'Swati': 'ssw_Latn',
    'Sundanese': 'sun_Latn',
    'Swedish': 'swe_Latn',
    'Swahili': 'swh_Latn',
    'Silesian': 'szl_Latn',
    'Tamil': 'tam_Taml',
    'Tamasheq (Latin)': 'taq_Latn',
    'Tamasheq (Tifinagh)': 'taq_Tfng',
    'Tatar': 'tat_Cyrl',
    'Telugu': 'tel_Telu',
    'Tajik': 'tgk_Cyrl',
    'Tagalog': 'tgl_Latn',
    'Thai': 'tha_Thai',
    'Tigrinya': 'tir_Ethi',
    'Tok Pisin': 'tpi_Latn',
    'Tswana': 'tsn_Latn',
    'Tsonga': 'tso_Latn',
    'Turkmen': 'tuk_Latn',
    'Tumbuka': 'tum_Latn',
    'Turkish': 'tur_Latn',
    'Twi': 'twi_Latn',
    'Tamazight': 'tzm_Tfng',
    'Uyghur': 'uig_Arab',
    'Ukrainian': 'ukr_Cyrl',
    'Umbundu': 'umb_Latn',
    'Urdu': 'urd_Arab',
    'Northern Uzbek': 'uzn_Latn',
    'Venetian': 'vec_Latn',
    'Vietnamese': 'vie_Latn',
    'Waray': 'war_Latn',
    'Wolof': 'wol_Latn',
    'Xhosa': 'xho_Latn',
    'Eastern Yiddish': 'ydd_Hebr',
    'Yoruba': 'yor_Latn',
    'Yue Chinese': 'yue_Hant',
    'Chinese (Simplified)': 'zho_Hans',
    'Chinese (Traditional)': 'zho_Hant',
    'Standard Malay': 'zsm_Latn',
    'Zulu': 'zul_Latn',
    'Filipino': 'fil_Latn',
    'Standard Moroccan Tamazight': 'zgh_Tfng',
    'Mandarin Chinese (Standard Beijing)': 'cmn_Hans',
    'Mandarin Chinese (Taiwanese)': 'cmn_Hant',
    'Wu Chinese': 'wuu_Hans',
    'Paraguayan Guaraní': 'gug_Latn',
    'Northern Estonian': 'ekk_Latn'
}

LANGCODE2LANGNAME = {v: k for k, v in LANGNAME2LANGCODE.items()}

EXPERIMENT8_LANGUAGES = ['West Central Oromo', 'Chinese (Simplified)', 'Chinese (Traditional)', 'Yue Chinese', 'Javanese', 'Sundanese', 'Burmese', 'Acehnese (Arabic)', 'Acehnese (Latin)', 'South Levantine Arabic', 'Amharic', 'North Levantine Arabic', 'MSA (Arabic)', 'MSA (Romanized)', 'Moroccan Arabic', 'Egyptian Arabic', 'Central Aymara', 'South Azerbaijani', 'North Azerbaijani', 'Balinese', 'Bengali', 'Banjar (Arabic script)', 'Banjar (Latin script)', 'Buginese', 'Bulgarian', 'Cebuano', 'Czech', 'Welsh', 'Danish', 'German', 'Greek', 'English', 'Fijian', 'French', 'Irish', 'Guarani', 'Gujarati', 'Hebrew', 'Hindi', 'Ilocano', 'Indonesian', 'Icelandic', 'Italian', 'Japanese', 'Kannada', 'Kazakh', 'Halh Mongolian', 'Khmer', 'Kikuyu', 'Northern Kurdish', 'Korean', 'Lao', 'Lithuanian', 'Ganda', 'Standard Latvian', 'Marathi', 'Minangkabau (Arabic)', 'Minangkabau (Latin)', 'Maori', 'Dutch', 'Odia', 'Southern Pashto', 'Western Persian', 'Polish', 'Portuguese', 'Ayacucho Quechua', 'Romanian', 'Russian', 'Sicilian', 'Slovak', 'Samoan', 'Spanish', 'Serbian', 'Swedish', 'Swahili', 'Tamil', 'Tatar', 'Telugu', 'Tagalog', 'Thai', 'Turkmen', 'Turkish', 'Uyghur', 'Ukrainian', 'Urdu', 'Northern Uzbek', 'Vietnamese', 'Waray', 'Xhosa', 'Standard Malay', 'Zulu']
EXPERIMENT8_LANGUAGE_CODES = [LANGNAME2LANGCODE[lang] for lang in EXPERIMENT8_LANGUAGES]

MODEL2NUM_LAYERS = {
    'gemma-3-1b-it': 26,
	'gemma-3-4b-it': 34,
    'gemma-3-270m-it': 18,
    'gemma-2-9b-it': 42,
    'gemma-3-12b-it': 48,
    'aya-expanse-8b': 32,
    'Llama-3.1-8B-Instruct': 32,
    'pythia-6.9b-deduped': 32,
    'Qwen3-14B': 40,
    'Qwen3-8B': 36,
    'aya-101': 24,
    'SmolLM3-3B': 36,
    'Qwen2.5-14B-Instruct': 48,
    'gpt-oss-20b': 24,
    'Qwen1.5-MoE-A2.7B-Chat': 24,
    'OLMo-2-1124-13B-Instruct': 40
}

MODEL2HIDDEN_SIZE = {
	'gemma-3-1b-it': 1152,
	'gemma-3-4b-it': 2560,
	'gemma-3-270m-it': 640,
    'gemma-2-9b-it': 3584,
    'gemma-3-12b-it': 3840,
    'aya-expanse-8b': 4096,
    'Llama-3.1-8B-Instruct': 4096,
    'pythia-6.9b-deduped': 4096,
    'Qwen3-14B': 5120,
    'Qwen3-8B': 4096,
    'aya-101': 4096,
    'SmolLM3-3B': 2048,
    'Qwen2.5-14B-Instruct': 5120,
    'gpt-oss-20b': 2880,
    'Qwen1.5-MoE-A2.7B-Chat': 2048,
    'OLMo-2-1124-13B-Instruct': 5120
}

MODEL2HF_NAME = {
    'gemma-3-1b-it': 'google',
    'gemma-3-4b-it': 'google',
    'gemma-3-270m-it': 'google',
    'gemma-2-9b-it': 'google',
    'gemma-3-12b-it': 'google',
    'aya-expanse-8b': 'CohereLabs',
    'Llama-3.1-8B-Instruct': 'meta-llama',
    'pythia-6.9b-deduped': 'EleutherAI',
    'Qwen3-14B': 'Qwen',
    'Qwen3-8B': 'Qwen',
    'aya-101': 'CohereLabs',
    'SmolLM3-3B': 'HuggingFaceTB',
    'Qwen2.5-14B-Instruct': 'Qwen',
    'gpt-oss-20b': 'openai',
    'Qwen1.5-MoE-A2.7B-Chat': 'Qwen',
    'OLMo-2-1124-13B-Instruct': 'allenai'
}
HF_NAME2MODEL = {v: k for k, v in MODEL2HF_NAME.items()}

EXP2_CONFIG = {
    'exp_id': 'exp2',
    'languages': {
        'Germanic': ["English", "German"],
        'Romance': ["Spanish", "French"], 
        'Semitic': ["MSA (Arabic)", "Hebrew"],
        'Slavic': ["Russian", "Slovak"],
        'Tai-Kadai': ["Thai", "Lao"],
        'Khmeric': ["Khmer"],
        'Vietic': ["Vietnamese"],
        'Bantu': ["Swahili", "Xhosa", "Zulu"],
        'Indo-Aryan': ["Urdu", "Hindi", "Kannada", "Telugu"],
        'Japonic': ["Japanese"],
        "Koreanic": ["Korean"],
        'Turkic': ["Turkish", "South Azerbaijani"],
        'Sinitic': ["Yue Chinese", 'Chinese (Simplified)'],
        'Malayic': ["Indonesian", "Standard Malay"]
    }
}

EXP2_CONFIG = {
    'exp_id': 'exp2',
    'languages': {
        'Germanic': ["English", "German"],
        'Romance': ["Spanish", "French"], 
        'Semitic': ["MSA (Arabic)", "Hebrew"],
        'Slavic': ["Russian", "Slovak"],
        'Tai-Kadai': ["Thai", "Lao"],
        'Khmeric': ["Khmer"],
        'Vietic': ["Vietnamese"],
        'Bantu': ["Swahili", "Xhosa", "Zulu"],
        'Indo-Aryan': ["Urdu", "Hindi", "Kannada", "Telugu"],
        'Japonic': ["Japanese"],
        "Koreanic": ["Korean"],
        'Turkic': ["Turkish", "South Azerbaijani", "North Azerbaijani"],
        'Philippine': ["Tagalog", "Cebuano", 'Ilocano', 'Waray'],
        'Sinitic': ["Yue Chinese", 'Chinese (Simplified)'],
        'Malayic': ["Indonesian", "Standard Malay", 
                    "Minangkabau (Latin)", "Minangkabau (Arabic)", 
                    "Banjar (Latin script)", "Banjar (Arabic script)"],
        'Javanesic': ['Javanese'],
        'Sundanese': ['Sundanese']
    }
}

# TODO: Add region information
EXP3_CONFIG = {
    'exp_id': 'exp3',
    'languages': {
        'West Germanic': ["English", "German", "Dutch"],
        'North Germanic': ['Swedish', 'Norwegian Bokmål', 'Icelandic'],
        'Romance': ["Spanish", "French", 'Italian', 'Portuguese', 'Romanian'], 
        'Semitic': ["MSA (Arabic)", "Hebrew", "Amharic"],
        'Berber': ['Tamazight', 'Tamasheq (Latin)', 'Tamasheq (Tifinagh)'],
        'Chadic': ['Hausa'],
        'Cushitic': ['Somali', 'West Central Oromo'], 
        'Uralic': ['Finnish', 'Hungarian', 'Estonian'],
        'East Slavic': ["Russian", "Ukrainian"],
        'South Slavic': ['Serbian', 'Bulgarian'],
        'West Slavic': ['Slovak', 'Polish', 'Czech'],
        'Baltic': ['Lithuanian', 'Standard Latvian'],
        'Tai-Kadai': ["Thai", "Lao"],
        'Khmeric': ["Khmer"],
        'Vietic': ["Vietnamese"],
        'Niger-Congo non-Bantu': ['Yoruba', 'Igbo'],
        'Niger-Congo Bantu': ["Swahili", "Xhosa", "Zulu"],
        'Indo-Aryan': ["Urdu", "Hindi", "Bengali", "Marathi"],
        'Dravidian': ['Tamil', 'Kannada', 'Telugu'],
        'Japonic': ["Japanese"],
        "Koreanic": ["Korean"],
        'Turkic': ["Turkish", "South Azerbaijani", "North Azerbaijani"],
        'Iranian': ['Western Persian', 'Northern Kurdish', 'Southern Pashto'],
        'Philippine': ["Tagalog", "Cebuano", 'Ilocano', 'Waray'],
        'Sinitic': ["Yue Chinese", 'Chinese (Simplified)'],
        'Malayic': ["Indonesian", "Standard Malay", 
                    "Minangkabau (Latin)", "Minangkabau (Arabic)", 
                    "Banjar (Latin script)", "Banjar (Arabic script)"],
        'Javanesic': ['Javanese'],
        'Sundanese': ['Sundanese'],
        'Quechuan': ['Ayacucho Quechua'],
        'Tupian': ['Guarani'],
        'Aymaran': ['Central Aymara'],
        'Oceanic': ['Fijian', 'Maori', 'Samoan']
    }
}

EXP4_CONFIG = {
    'exp_id': 'exp4',
    'languages': {
        'West Germanic': ["English", "German", "Dutch"],
        'North Germanic': ['Swedish', 'Norwegian Bokmål', 'Icelandic'],
        'Romance': ["Spanish", "French", 'Italian', 'Portuguese', 'Romanian'], 
        'Semitic': ["MSA (Arabic)", "Hebrew", "Amharic"],
        'Berber': ['Standard Moroccan Tamazight', 'Tamasheq (Latin)', 'Tamasheq (Tifinagh)'],
        'Chadic': ['Hausa'],
        'Cushitic': ['Somali', 'West Central Oromo'], 
        'Uralic': ['Finnish', 'Hungarian', 'Northern Estonian'],
        'East Slavic': ["Russian", "Ukrainian"],
        'South Slavic': ['Serbian', 'Bulgarian'],
        'West Slavic': ['Slovak', 'Polish', 'Czech'],
        'Baltic': ['Lithuanian', 'Standard Latvian'],
        'Tai-Kadai': ["Thai", "Lao"],
        'Khmeric': ["Khmer"],
        'Vietic': ["Vietnamese"],
        'Niger-Congo non-Bantu': ['Yoruba', 'Igbo'],
        'Niger-Congo Bantu': ["Swahili", "Xhosa", "Zulu"],
        'Indo-Aryan': ["Urdu", "Hindi", "Bengali", "Marathi"],
        'Dravidian': ['Tamil', 'Kannada', 'Telugu'],
        'Japonic': ["Japanese"],
        "Koreanic": ["Korean"],
        'Turkic': ["Turkish", "South Azerbaijani", "North Azerbaijani"],
        'Iranian': ['Western Persian', 'Northern Kurdish', 'Southern Pashto'],
        'Philippine': ["Filipino", "Cebuano", 'Ilocano', 'Waray'],
        'Sinitic': ["Mandarin Chinese (Standard Beijing)", 'Yue Chinese', 'Mandarin Chinese (Taiwanese)', 'Wu Chinese'],
        'Malayic': ["Indonesian", "Standard Malay", 
                    "Minangkabau (Latin)", "Minangkabau (Arabic)", 
                    "Banjar (Latin script)", "Banjar (Arabic script)"],
        'Javanesic': ['Javanese'],
        'Sundanese': ['Sundanese'],
        'Quechuan': ['Ayacucho Quechua'],
        'Tupian': ['Paraguayan Guaraní'],
        'Aymaran': ['Central Aymara'],
        'Oceanic': ['Fijian', 'Maori', 'Samoan'],
        'Armenian': ['Armenian'],
    }
}
# Change json structure to 'languages' -> 'language_name' -> {'language_code', 'family', 'syntax', 'script', 'region'}
# Change to FLORES+, add Wu Chinese